<div class="marquee-wrap">
  <div class="marquee-track">
    <span class="marquee-item">UX Design <span>✦</span></span>
    <span class="marquee-item">UI Design <span>✦</span></span>
    <span class="marquee-item">Web Design <span>✦</span></span>
    <span class="marquee-item">Desenvolvimento Full Stack <span>✦</span></span>
    <span class="marquee-item">HTML <span>✦</span></span>
    <span class="marquee-item">CSS <span>✦</span></span>
    <span class="marquee-item">JavaScript <span>✦</span></span>
    <span class="marquee-item">PHP <span>✦</span></span>
    <span class="marquee-item">Python <span>✦</span></span>
    <span class="marquee-item">Figma <span>✦</span></span>
    <span class="marquee-item">WordPress <span>✦</span></span>
    <span class="marquee-item">Framer <span>✦</span></span>
    <span class="marquee-item">Design System <span>✦</span></span>
    <span class="marquee-item">UX Design <span>✦</span></span>
    <span class="marquee-item">UI Design <span>✦</span></span>
    <span class="marquee-item">Web Design <span>✦</span></span>
    <span class="marquee-item">Desenvolvimento Full Stack <span>✦</span></span>
    <span class="marquee-item">HTML <span>✦</span></span>
    <span class="marquee-item">CSS <span>✦</span></span>
    <span class="marquee-item">JavaScript <span>✦</span></span>
    <span class="marquee-item">PHP <span>✦</span></span>
    <span class="marquee-item">Python <span>✦</span></span>
    <span class="marquee-item">Figma <span>✦</span></span>
    <span class="marquee-item">WordPress <span>✦</span></span>
    <span class="marquee-item">Framer <span>✦</span></span>
    <span class="marquee-item">Design System <span>✦</span></span>
  </div>
</div>